# Generated by Django 2.0.7 on 2019-04-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recapp.Recruter'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recapp.Task'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='New Task', max_length=120, unique=True),
        ),
    ]
