# Generated by Django 2.0.7 on 2019-04-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recapp', '0002_auto_20190421_1319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('task', 'candidate')},
        ),
    ]
